name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  windows:
    strategy:
      matrix:
        arch: ["x86-64-vnni512", "x86-64-bmi2", "x86-64-modern"]
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      - name: make largeboards
        run: cd src && make clean && make -j build COMP=mingw ARCH=${{ matrix.arch }} EXE=${{ matrix.arch }}.exe largeboards=yes && strip ${{ matrix.arch }}.exe

      - uses: actions/upload-artifact@v3
        with:
          name: fairy-stockfish
          path: src/x86-64-*.exe
